name: Links

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --config lychee.toml './README.md'
          fail: true
